### ISSUE TITLE
[FeatureRequest]

### ISSUE THREAD

**Issue by jfrog88** [AndreasReitberger/RemoteControlRepetierServerProApp#10]
**Is your feature request related to a problem? Please describe.**

Need an Amazon Echo (Alexa) Skill where sending push messages like "Printing ist finished" or something like that :) 

**Describe the solution you'd like**

Maybe code one 😂

**Describe alternatives you've considered**

Do not try any alternatives. Ifttt is no alternative because I won't buy an premium account on ifttt.

**Additional context**

Thanks for your attention :)

**Comment by AndreasReitberger** [comment]
Hi @jfrog88 
I'm sorry, but I do not develop Skills for Alexa. 
More is this something what needs to be done directly on the Repetier Server / Raspi.

Best, 
Andreas
