### ISSUE TITLE
iOS Beta

### ISSUE THREAD

**Issue by Tw0bit** [AndreasReitberger/RemoteControlRepetierServerProApp#11]
Sorry, was not sure the best way to ask about the iOS Beta. The posted link doesnt seem to work.

**Comment by AndreasReitberger** [comment]
Hi @Tw0bit 
the beta for the free version is currently disabled, because there is no new version for testing.
However you can join the Pro beta (for free) here.

https://testflight.apple.com/join/qIH1zd5T

Once the pro version is ready for the live release, the free version will be updated as well.
