### ISSUE TITLE
DNS Name is not resolved properly

### ISSUE THREAD

**Issue by peer69** [AndreasReitberger/RemoteControlRepetierServerProApp#15]
I cannot connect to a Repetier Server instance by its internal DNS name. 
Does the app force to use a public dns server causing it to ignore the dns set in the system settings (my host is only resolved by the internal dns server)? 

When I click the link next to the server name/ip setting the servers page opens in the browser just fine. Connection via IP address works fine as well.

**Comment by AndreasReitberger** [comment]
Hello,
What FQDN did you enter? Did you use "repetier-server.local"? 

You can try to go to the settings-> Server -> Add new.

Here, enter the FQDN which is not working and click add. The app tries now to connect.
If it fails, please go to the "Event Manager" in the main menu and check if there is a related warning / error.
Can you share the error log with me?

I'll check it then.

Best,
Andreas

**Comment by peer69** [comment]
My internal FQDN is RepetierServer.home.peer69.de this does not work. It resolves fine though through my internal dns server which every client device should use as it’s announced by the dhcp-server, might be an issue with the sub-sub-domain I use. 
hadn’t tried RepetierServer.local yet, but it works.

The event log stays empty.

**Comment by peer69** [comment]
![C5D861D3-3F1B-428D-B1BA-43A7688D1CD8](https://user-images.githubusercontent.com/28559804/147696784-c8d447a9-639a-408f-bb9c-7da26dfe8b36.png)
![8F832927-88B4-422A-9D9E-E373E5523EF9](https://user-images.githubusercontent.com/28559804/147696795-75d9c658-41b8-47ec-a1f6-b931c14981b8.png)
![Uploading 8D1460B7-EDD6-4A70-BEBE-EAEFC12C7050.png…]()

**Comment by peer69** [comment]
![FDD38F5D-84DB-47EA-889A-F1AAF81D117B](https://user-images.githubusercontent.com/28559804/147696852-173d00fa-f3b3-497a-86e5-5a65c3b1f12e.png)

**Comment by AndreasReitberger** [comment]
Thanks for the update. I'll check the source code and keep you posted.

If it works from your browser, it should also do so in the App.

Best,
Andreas

**Comment by AndreasReitberger** [comment]
Hi again,
I prepared a small desktop tool allowing you to simulate the online connection check.
Please find it here.

https://github.com/AndreasReitberger/RemoteControlRepetierServerProApp/blob/master/Tools/ConnectionTest/RepetierConnectionTest.zip

Run the .exe inside the zip and enter your FQDN. When you click "Connect", there should be an error message in the right text box.

![image](https://user-images.githubusercontent.com/2952443/147731789-6ea72e65-24b0-4278-bf86-5950c00a3f0c.png)

Let me know what the result is.

Thank you,
Andreas

**Comment by peer69** [comment]
This is odd. Using the windows app (disclaimer: I had to use a VM in bridge mode as I don't use windows on any machine) the FQDN which doesn't work in the iOS App works. RepetierServer.local as a hostname which does work in the iOS app doesn't. 

> Connection to http://repetierserver.home.peer69.de:3344 was successfully establised!
> Error while connecting to http://repetierserver.local:3344!
> Message: System.Net.Sockets.SocketException (11004): Der angeforderte Name ist gültig, es wurden jedoch keine Daten des angeforderten Typs gefunden.
>    at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses)
>    at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
>    at AndreasReitberger.RepetierServerPro.CheckOnlineAsync(CancellationTokenSource cts, Boolean resolveDnsFirst) in C:\Users\andyr\Documents\GitHub\RepetierServerSharpApi\source\RepetierServerSharpApi\RepetierServerSharpApi\RepetierServerPro.cs:line 3276
> Error while connecting to http://repetierserver.local:3344!
> Message: System.Net.Http.HttpRequestException: Der angeforderte Name ist gültig, es wurden jedoch keine Daten des angeforderten Typs gefunden. (repetierserver.local:3344)
>  ---> System.Net.Sockets.SocketException (11004): Der angeforderte Name ist gültig, es wurden jedoch keine Daten des angeforderten Typs gefunden.
>    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
>    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
>    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
>    at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
>    at AndreasReitberger.RepetierServerPro.CheckOnlineAsync(CancellationTokenSource cts, Boolean resolveDnsFirst) in C:\Users\andyr\Documents\GitHub\RepetierServerSharpApi\source\RepetierServerSharpApi\RepetierServerSharpApi\RepetierServerPro.cs:line 3288
> Error while connecting to http://repetierserver.local:3344!
> Message: System.Net.Sockets.SocketException (11004): Der angeforderte Name ist gültig, es wurden jedoch keine Daten des angeforderten Typs gefunden.
>    at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses)
>    at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
>    at AndreasReitberger.RepetierServerPro.CheckOnlineAsync(CancellationTokenSource cts, Boolean resolveDnsFirst) in C:\Users\andyr\Documents\GitHub\RepetierServerSharpApi\source\RepetierServerSharpApi\RepetierServerSharpApi\RepetierServerPro.cs:line 3276
> Error while connecting to http://repetierserver.local:3344!
> Message: System.Net.Http.HttpRequestException: Der angeforderte Name ist gültig, es wurden jedoch keine Daten des angeforderten Typs gefunden. (repetierserver.local:3344)
>  ---> System.Net.Sockets.SocketException (11004): Der angeforderte Name ist gültig, es wurden jedoch keine Daten des angeforderten Typs gefunden.
>    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
>    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
>    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
>    at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
>    at AndreasReitberger.RepetierServerPro.CheckOnlineAsync(CancellationTokenSource cts, Boolean resolveDnsFirst) in C:\Users\andyr\Documents\GitHub\RepetierServerSharpApi\source\RepetierServerSharpApi\RepetierServerSharpApi\RepetierServerPro.cs:line 3288
> Error while connecting to http://repetierserver.local:3344!
> Message: System.Net.Sockets.SocketException (11004): Der angeforderte Name ist gültig, es wurden jedoch keine Daten des angeforderten Typs gefunden.
>    at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses)
>    at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
>    at AndreasReitberger.RepetierServerPro.CheckOnlineAsync(CancellationTokenSource cts, Boolean resolveDnsFirst) in C:\Users\andyr\Documents\GitHub\RepetierServerSharpApi\source\RepetierServerSharpApi\RepetierServerSharpApi\RepetierServerPro.cs:line 3276
> Error while connecting to http://repetierserver.local:3344!
> Message: System.Net.Http.HttpRequestException: Der angeforderte Name ist gültig, es wurden jedoch keine Daten des angeforderten Typs gefunden. (repetierserver.local:3344)
>  ---> System.Net.Sockets.SocketException (11004): Der angeforderte Name ist gültig, es wurden jedoch keine Daten des angeforderten Typs gefunden.
>    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
>    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
>    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
>    at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
>    at AndreasReitberger.RepetierServerPro.CheckOnlineAsync(CancellationTokenSource cts, Boolean resolveDnsFirst) in C:\Users\andyr\Documents\GitHub\RepetierServerSharpApi\source\RepetierServerSharpApi\RepetierServerSharpApi\RepetierServerPro.cs:line 3288
> Error while connecting to http://repetierserver.local:3344!
> Message: System.Net.Sockets.SocketException (11004): Der angeforderte Name ist gültig, es wurden jedoch keine Daten des angeforderten Typs gefunden.
>    at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses)
>    at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
>    at AndreasReitberger.RepetierServerPro.CheckOnlineAsync(CancellationTokenSource cts, Boolean resolveDnsFirst) in C:\Users\andyr\Documents\GitHub\RepetierServerSharpApi\source\RepetierServerSharpApi\RepetierServerSharpApi\RepetierServerPro.cs:line 3276
> Error while connecting to http://repetierserver.local:3344!
> Message: System.Net.Http.HttpRequestException: Der angeforderte Name ist gültig, es wurden jedoch keine Daten des angeforderten Typs gefunden. (repetierserver.local:3344)
>  ---> System.Net.Sockets.SocketException (11004): Der angeforderte Name ist gültig, es wurden jedoch keine Daten des angeforderten Typs gefunden.
>    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
>    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
>    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
>    at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
>    at AndreasReitberger.RepetierServerPro.CheckOnlineAsync(CancellationTokenSource cts, Boolean resolveDnsFirst) in C:\Users\andyr\Documents\GitHub\RepetierServerSharpApi\source\RepetierServerSharpApi\RepetierServerSharpApi\RepetierServerPro.cs:line 3288
> Connection to http://repetierserver.local:3344 failed!
>

**Comment by AndreasReitberger** [comment]
Thanks for the update.
That's indeed a strange behaviour. However, the tool I sent you is using a new method to check the online state.
It tries first to resolve the hostname before sending the request.
If the resolve pass, the IP will be used instead.

This is the current code for checking the online state.
```cs
string uriString = FullWebAddress;
try
{
    // This will try to resolve the hostname before sending the reqeuest.
    if (resolveDnsFirst)
    {
        try
        {
            IPHostEntry host = Dns.GetHostEntry(ServerAddress);
            IPAddress address = host.AddressList.FirstOrDefault(ip => ip.AddressFamily == System.Net.Sockets.AddressFamily.InterNetwork);
            if(address != null)
            {
                uriString = $"{(IsSecure ? "https" : "http")}://{address}:{Port}";
            }
        }
        catch (Exception exc)
        {
            OnError(new UnhandledExceptionEventArgs(exc, false));
        }
    }

    HttpResponseMessage response =
        await client.GetAsync(uriString, HttpCompletionOption.ResponseHeadersRead, cts.Token).ConfigureAwait(false);
    response.EnsureSuccessStatusCode();
    if (response != null)
    {
        isReachable = response.IsSuccessStatusCode;
    }
    await Task.Delay(50);
}
catch (InvalidOperationException iexc)
{
    OnError(new UnhandledExceptionEventArgs(iexc, false));
}
catch (HttpRequestException rexc)
{
    OnError(new UnhandledExceptionEventArgs(rexc, false));
}
catch (TaskCanceledException)
{
    // Throws an exception on timeout, not actually an error
}
```

The `Dns.GetHostEntry()` method uses the public dns server from your network adapter. So this might be the reason why it works on your computer, but not on your phone.

If you visit both addresses on your computer with the browser, both are working?

**Comment by peer69** [comment]
The windows machine cannot resolve repetierserver.local. This might just be an issue with it being a VM or missing MDNS-stuff under Windows 7 which was the only VM I had available: 
<img width="356" alt="image" src="https://user-images.githubusercontent.com/28559804/147749741-d62c21f9-51e3-49d2-b05e-71b7ed0e29bc.png">

On my mac which I use as the host for the VM, both, repetierserver.home.peer69.de and repetierserver.local work fine. Resolution works as shown and the browser can reach the interface using both addresses as well. 
<img width="638" alt="image" src="https://user-images.githubusercontent.com/28559804/147750271-ce9dc0a4-2003-41da-b901-212569ba9d0b.png">

Name Resolution on my iPhone looks like this: 
![image](https://user-images.githubusercontent.com/28559804/147750433-4ff91bcf-d6d8-43bc-b4b1-6ae8f7e67b1d.png)
It uses the standard dns server provided by DHCP and resolves the host just fine. I use several other apps with services hosted internally and I haven't experienced any resolution errors with my internal hostnames yet.

**Comment by AndreasReitberger** [comment]
Ok I see, so that "http://repetierserver.local:3344" also isn't working on your VM, I assume that the new approach is working.
I'll prepare a new update using the new approach for the iOS app and push it to TestFlight.

You can access the update over this link once it is available: https://testflight.apple.com/join/qIH1zd5T

I hope to get it done this weekend. I'll keep you posted once it's ready.
Please verify if the issue persists and report back.

In the meantime, please use the IP address or the working FQDN for the app. 
Sorry for the inconveniences caused with this issue.

**Comment by peer69** [comment]
Great, thank you very much for looking into it! I will check as soon as the new version is ready.

**Comment by AndreasReitberger** [comment]
Hi @peer69 
The new build is no in review by apple.
I found another way to make the online check, please let me know if this works as well for you.

The previous approach lead to freezes on the ui thread if the host was offline (for real).

You will be notified by TestFlight once the build has been approved.

Best,
Andreas

**Comment by peer69** [comment]
The new version seems to be working. I will mark the issue as closed. Thank you for fixing this! 
Happy new year, btw. :) 

![1A640FF3-3513-4B45-B971-B4DD91F58398](https://user-images.githubusercontent.com/28559804/147847100-f4a9dd4a-29d8-4f18-8724-bf1cea176b1c.png)
