### ISSUE TITLE
[FeatureRequest]

### ISSUE THREAD

**Issue by RainerBavaria** [AndreasReitberger/RemoteControlRepetierServerProApp#16]
Guten Tag , 
Ich finde die RepetierApp einfach genial und super ,
Erstmal danke dafür.

Einzig ein Feature vermisse ich .
Man kann am PC die Einstellung "Nach dem Druck herunterfahren" auswählen, diese Möglichkeit gibt es leider in der App nicht .
Ich persönlich würde es aber toll finden, 
um komplett autark mit der App arbeiten zu können .
![20220202_065922.jpg](https://user-images.githubusercontent.com/98868798/152101707-dc5b059e-7f1f-4fed-a788-5b381a902a83.jpg)

Bei Fragen kommt gerne auf mich zu .
Danke
RainerBavaria

**Comment by AndreasReitberger** [comment]
Hallo @RainerBavaria 
danke für deinen Vorschlag und positives Feedback zur App.
Ich habe den Punkt mit aufgenommen und werde das beim nächsten Update versuchen umzusetzen.

Sofern Repetier Server hier eine Schnittstelle bietet, kann ich das ohne weiteres auch in der App abbilden.

Viele Grüße,
Andreas

**Comment by AndreasReitberger** [comment]
Hallo @RainerBavaria 
Dein Vorschlag wurde übernommen und ist mit der nächsten Version (Pro 1.2.8-v2) verfügbar.
Diese sollte nächste Woche über TestFlight verfügbar sein.

![image](https://user-images.githubusercontent.com/2952443/155744003-7a2fa253-e90a-4c3f-b3ff-a1287a2bd6fe.png)
