### ISSUE TITLE
[Bug] Webcam disabled after app restart

### ISSUE THREAD

**Issue by armin771** [AndreasReitberger/RemoteControlRepetierServerProApp#17]
**Describe the bug**
Every time I restart the app and go to the webcam tab, it says to enable the webcam in the settings. I then do that as well. But every time I restart the app, I have to reactivate the webcam.

**To Reproduce**
1. Go to Webcam
2. Click on Settings
3. Scroll down to "WebCam aktivieren"
4. Activate Webcam
5. Restart App
6. Do it again

**Expected behavior**
Save that, the webcam has been activated

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS 15.5
 - App Version: 1.2.7

**Comment by AndreasReitberger** [comment]
Hi @armin771 
Thanks for your error report. This is already fixed in 1.2.8.
For a workaround, you can disable the iCloud sync till the update is ready.
I'll push an update to TestFlight, so that you can double check the fix.
- [x] Fix issue
- [x] Push 1.2.8 to TestFlight 

I'll keep you posted.

Best,
Andreas

**Comment by armin771** [comment]
Thank you for the quick reply. Can I join the beta in TestFlight? When I click on the TestFlight link (iOS Pro Version) in the readme, it says that no new testers are accepted.

**Comment by AndreasReitberger** [comment]
Yes, once the new version is available, you can join via TestFlight again.
I'll let you know here, when testing is ready 😃

**Comment by AndreasReitberger** [comment]
Hi @armin771 
The test is available now and you should be able to join TestFlight.

Best,
Andreas

**Comment by armin771** [comment]
Thank you really much. I could install the beta and now it works 😊

**Comment by AndreasReitberger** [comment]
Glad to hear, the beta version will be around 2-3 weeks under testing. If no other issue shows up, it will go to the production release then.
I'll close this issue. If you figure something out, please feel free to open a new issue.

Best,
Andreas
