### ISSUE TITLE
[FeatureRequest] Schnellbefehle bei Webcam 

### ISSUE THREAD

**Issue by breefube** [AndreasReitberger/RemoteControlRepetierServerProApp#22]
Zuerst ich liebe Ihre App.
5 Sterne werde ich auch noch im AppStore geben.
Könnten Sie hinzufügen das man ein weiteren Button hat in der Steuerzentrale bei der Webcam um die Liste der Schnellbefehle aufzulisten und aufzurufen.
Ich habe hier zum Beispiel Licht an und aus ist sehr viel bequemer dann.
Danke

**Comment by AndreasReitberger** [comment]
Hallo @breefube 
Vielen Dank erstmal für Ihre Bewertung und nettes Feedback. Es freut mich, dass Ihnen die App so gut gefällt.

Ich arbeite aktuell eh am Update 1.2.9 und an der komplett neuen Version 1.3.0 (neues Framework, komplett neu programmiert). Ich werde Ihren Vorschlag bei beiden Versionen berücksichtigen :)
Die Version 1.2.9 sollte demnächst verfügbar sein. Ich gebe Ihnen hier Bescheid, sobald die Funktion eingebunden und das Update verfügbar ist.

Viele Grüße,
Andreas

Internes Tracking:

- [x] https://github.com/AndreasReitberger/RemoteControlRepetierServerProMaui/issues/27 (1.3.0-preview)
- [x] https://github.com/AndreasReitberger/RemoteControlRepetierServerPro/issues/38 (1.2.9)

**Comment by AndreasReitberger** [comment]
Hallo @breefube 

Ich hab heute begonnen, die Schnellbefehle auch in der Steuerzentrale verfügbar zu machen.
Dies wäre mal mein aktueller Vorschlag. Entspricht das Ihren Erwartungen?
Das Modul zeigt maximal 3 Befehle an, alle anderen bekommen Sie, wenn Sie auf das Modul klicken (siehe Screenshot 2)

![2023-01-28_03-51-55-](https://user-images.githubusercontent.com/2952443/215273200-30dc18f5-cc93-4c2f-9100-0a8cbdcb84f9.png)
![2023-01-28_03-51-59-](https://user-images.githubusercontent.com/2952443/215273202-99d5d791-8e18-4551-bf6d-f0545a5950f5.png)

Bitte geben Sie kurz Rückmeldung ob das für Sie so passt :)

**Comment by breefube** [comment]
Hallo Herr Reitberger,
richtig cool.
Besser wie ich es mir vorgestellt habe :)
Grüße Björn

Andreas ***@***.***> schrieb am Sa., 28. Jan. 2023, 15:55:

**Comment by AndreasReitberger** [comment]
Hallo Björn (@breefube)
Ich habe eben die Version 1.2.9 in das Beta-Programm hochgeladen. Die App muss nur noch von Google überprüft werden, ab dann steht die Version zum Test bereit. Sollten Sie noch kein Beta-Tester sein, dann können Sie einfach über folgenden Link einsteigen und teilnehmen:
https://play.google.com/store/apps/details?id=com.andreasreitberger.repservapppro

Sollten Sie Probleme mit der Beta oder den neuen Funktionen haben, bitte einfach hier Bescheid geben. Ich lasse den Issue so lange offen.

Viele Grüße,
Andreas

**Comment by breefube** [comment]
Vielen Dank.
Habe mich gleich als Betatester registriert.
Grüße Björn

Andreas ***@***.***> schrieb am Mo., 30. Jan. 2023, 16:57:

**Comment by breefube** [comment]
Kurz Zur Info zu den Bewertungen bei Google
Ich nutze die App über eine Portfreigabe an einem Dualstack Anschluss über
DynDns mit SSL Zertifikat und habe keine Probleme. Der Verbindungsaufbau
ist super. Ich kann mich nicht beschweren.
Ich denke es fehlt einfach etwas an wissen.
Grüße Björn

Björn Bauer ***@***.***> schrieb am Mo., 30. Jan. 2023, 16:58:

**Comment by AndreasReitberger** [comment]
Danke für Ihr Feedback dazu. Ja leider ist schneller eine schlechte Bewertung geschrieben, als einfach Kontakt mit mir aufzunehmen. Dabei würde ich jeden gerne dazu Helfen ;) Das die App natürlich auch Bugs habe kann, ist nie ausgeschlossen. Aber nur durch schlechte Bewertungen, wie "Geht nicht" kann ich halt auch keinen Fehler beheben ;) Schön das es aber auch noch andere Leute gibt!

Viele Grüße,
Andreas

**Comment by breefube** [comment]
Was vielleicht sinnvoll wäre, schreiben Sie dazu dass die App über den Port
3344 kommuniziert und nicht über die Standard http-ports 80 und 443, so
dass das gegebenenfalls in Firewalls freigegeben werden muss bei Fragen
gerne nachhaken.
Grüße

Andreas ***@***.***> schrieb am Mo., 30. Jan. 2023, 17:10:

**Comment by breefube** [comment]
Mir ist noch aufgefallen, dass ausgeblendete Schnellbefehle (Ausgeblendet
währende dem Druck) trotzdem angezeigt werden.
An sich sonst klappt es :)

Am Do., 26. Jan. 2023 um 06:12 Uhr schrieb Andreas ***@***.***

**Comment by AndreasReitberger** [comment]
Hallo Björn, 
Danke für den Hinweis. Dies ist mir gar nicht aufgefallen, dass man das unterscheiden kann. Passe ich auf jeden Fall noch an :) danke für deine Rückmeldung!

Viele Grüße,
Andreas

**Comment by breefube** [comment]
Hi Andreas,
Was cool wäre könnte man die Schnellbefehle auch nutzen wenn der Drucker
aus ist ohne auf die Konsole zu gehen, da ich mit diesen ein Relay
fernsteuere was Licht usw. steuert.
Grüße Björn

Andreas ***@***.***> schrieb am Do., 2. Feb. 2023, 05:10:

**Comment by AndreasReitberger** [comment]
Hi Björn,

nehme ich noch mit auf fürs nächste Update ;)

Viele Grüße,
Andreas

**Comment by breefube** [comment]
Perfekt danke dir hast du irgendwo implementiert das man anhaken kann
Drucker herunterfahren nach Druck?
Geht am Repetier online :)
Grüßle

Andreas ***@***.***> schrieb am Sa., 4. Feb. 2023, 18:17:

**Comment by AndreasReitberger** [comment]
Hallo Björn,
ja, das sollte schon funktionieren. Dazu einfach den aktuellen Druck öffnen (In der Titelanzeige auf den Druckfortschritt klicken).

Dort einfach setzen, dass der Drucker heruntergefahren werden soll.
![2023-02-09_06-33-55-](https://user-images.githubusercontent.com/2952443/217892662-5b25223e-df47-4aeb-84c2-b7382eb5a3b1.png)

**Comment by AndreasReitberger** [comment]
Hallo Björn,

Befehle sind nun auch bei offlinen Drucker verfügbar. Des Weiteren berücksichtigt die App nun, ob der Befehl beim Druck sichtbar ist oder nicht. 
Ich bereite gerade das Update vor, es sollte demnächst über die AppStores (Beta-Tester) verfügbar sein.

![2023-02-10_06-37-57-](https://user-images.githubusercontent.com/2952443/218014459-97f5cf93-ad20-4820-93c5-53da279ef813.png)
![2023-02-10_06-51-25-](https://user-images.githubusercontent.com/2952443/218014473-a6fe85e8-3fea-4900-bc59-e25054188413.png)

**Comment by breefube** [comment]
Danke dir freue mich auf das Update.
Grüße

Andreas ***@***.***> schrieb am Fr., 10. Feb. 2023, 07:49:
