### ISSUE TITLE
[Bug] Scrolling not possible due to `RefreshView`

### ISSUE THREAD

**Issue by breefube** [AndreasReitberger/RemoteControlRepetierServerProApp#23]
**Describe the bug**
Wenn ich versuche in der Steuerzentrale wieder ganz hoch zu gehen nachdem ich runter gegangen bhin will er immer aktualisieren.
Vlt. einen Aktualisieren Button statt dem herunterziehen machen. 

**To Reproduce**
Steuerzentrale -> Scrolle ganz runter -> versuche wieder hochzu scrollen

**Expected behavior**

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://user-images.githubusercontent.com/58933204/218302123-e23a13f9-2c9b-4186-8a54-b0df7c21a35b.mp4)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
Xiaomi 12 Miui 14 Android 13
**Additional context**

**Comment by AndreasReitberger** [comment]
Hi Björn,

ist mir tatsächlich auch schon passiert. Scheinbar ist das aber nicht immer ein Problem.
Ich werde das in der v1.2.9 noch mit aufnehmen.

Internes Tracking:
- [ ] https://github.com/AndreasReitberger/RemoteControlRepetierServerPro/issues/59

**Comment by breefube** [comment]
Hi Andreas,
Ist mir so aufgefallen :)
Ist jetzt nicht so störend dachte ich melde es Mal.
Grüße

Andreas ***@***.***> schrieb am So., 12. Feb. 2023, 11:46:

**Comment by AndreasReitberger** [comment]
Hallo Björn,

hab das in der Version 1.2.9.2 angepasst :) Du findest nun in der Topbar einen Refresh-Button.
Das Ziehen zum Aktualisieren wurde auf dieser Seite deaktiviert.

Gib Bescheid, ob das nun zuverlässig funktioniert ;)
Danke!

**Comment by breefube** [comment]
Servus Andreas,
klappt sehr gut.
Danke dir :)
Sollte noch was sein melde ich mich.
Grüße
Björn

Andreas ***@***.***> schrieb am Sa., 18. Feb. 2023, 17:45:
