### ISSUE TITLE
Geht aus nach update

### ISSUE THREAD

**Issue by chuckxxxl** [AndreasReitberger/RemoteControlRepetierServerProApp#24]
**Describe the bug**

**To Reproduce**

**Expected behavior**

App öffnet, aber oben in der Leiste ist kein App Symbol, sobald man eine andere App öffnet, geht diese aus ohne im Hintergrund weiterzulaufen
**Screenshots**

![Screenshot_20230216_142828_Device care](https://user-images.githubusercontent.com/21015958/219378232-5e71a759-adbe-4884-a719-df3433493e63.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] S23 ultra 

**Additional context**

**Comment by AndreasReitberger** [comment]
Hallo @chuckxxxl 

Ich glaub ich hab dein Feedback bereits über Google Play erhalten und darauf geantwortet.
Ich hab den Fehler intern geloggt und bereite ein Update dazu vor.

Internes Tracking:
- [ ] https://github.com/AndreasReitberger/RemoteControlRepetierServerPro/issues/60

Ich geb hier bescheid, sobald ich das Problem behoben hab. Danke für den Hinweis!

**Comment by AndreasReitberger** [comment]
Hallo @chuckxxxl 

Das Problem ist hier `Android 12+`. Ab hier darf eine App keinen ForegroundService mehr aus dem Hintergrund erstellen.
Hier muss ich erst eine neue Möglichkeit implementieren, dass auch unter Android 12+ lauffähig zu bekommen.
Um die Abstürze zu verhindern, kannst du in den Einstellungen unter "Vordergrundservice" diesen temporär deaktivieren.

Ich arbeite aktuell an einer Lösung.

**Comment by AndreasReitberger** [comment]
Hallo @chuckxxxl 
Fehler wurde nun behoben und die Funktion für Android 12+ angepasst. Update steht nach Freigabe von Google bereit, was in der Regel ca. 1 Tag dauert.
Bitte gib hier Bescheid, ob der Fehler für dich behoben ist.

Danke fürs Melden!

**Comment by chuckxxxl** [comment]
Läuft wieder gewohnt super. Danke dir. Hast du ein changelog was in Version 1.4.9 geupdatet wurde?

**Comment by AndreasReitberger** [comment]
Danke für deine Rückmeldung, freut  mich, dass wieder alles wie gewohnt funktioniert.
Changelog findest du in der App unter "Über" (Hauptmenü), dann unten auf die Versionsnummer klicken oder hier: 
https://andreas-reitberger.de/apps/remote-control-repetier-server-pro/rc-repetier-changelog/#version-1-2-9-beta

Viele Grüße
Andreas
