### ISSUE TITLE
[Bug] Extruder temp not fixed.

### ISSUE THREAD

**Issue by Chazy12** [AndreasReitberger/RemoteControlRepetierServerProApp#6]
On the last beta, the extruder temperature it's not working correctly.

https://drive.google.com/file/d/106YozL48TgO2PoXD7aJLc3gy7nBEr6Ip/view?usp=drivesdk

**Comment by AndreasReitberger** [comment]
> On the last beta, the extruder temperature it's not working correctly.
> 
> https://drive.google.com/file/d/106YozL48TgO2PoXD7aJLc3gy7nBEr6Ip/view?usp=drivesdk

Hi,
thanks for letting me know. Can you grant me access the shared link? I sent you a request via Google.
Thanks!

**Comment by Chazy12** [comment]
Did it. Sorry, i didn't set the shared option.

Chazy
Il 11 feb 2021, 06:13 +0100, Andreas <notifications@github.com>, ha scritto:

**Comment by AndreasReitberger** [comment]
> Did it. Sorry, i didn't set the shared option. Chazy Il 11 feb 2021, 06:13 +0100, Andreas <notifications@github.com>, ha scritto:
> […](#)
> > On the last beta, the extruder temperature it's not working correctly. > https://drive.google.com/file/d/106YozL48TgO2PoXD7aJLc3gy7nBEr6Ip/view?usp=drivesdk Hi, thanks for letting me know. Can you grant me access the shared link? I sent you a request via Google. Thanks! — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you, I'll check and fix it ;)

**Comment by AndreasReitberger** [comment]
Hi @Chazy12 
I tested the latest version 1.0.19 on my iPhone and Android phone. There it's working fine. What version have you installed?
Also, is there any issue in the "Event Manager" shown? If you have some steps to reproduce the issue, just let me know.

**Comment by Chazy12** [comment]
It was last beta on Android. I had to uninstall it couse, everytime I opened it, my printers stop printing. I don't know if the app send some code, but the printers stops working.

Chazy
Il 11 feb 2021, 13:40 +0100, Andreas <notifications@github.com>, ha scritto:

**Comment by AndreasReitberger** [comment]
Thanks for your update. That shouldn't happen either. However the app isn't sending any code on startup, so the print job shouldn't be interupted at all. It just connects to the Servers websocket. 

I'll further investigate this behaviour. Maybe I can reproduce it with my setup. Maybe you can try the app again, to be sure, wait till the printer has finished its job first.

**Comment by AndreasReitberger** [comment]
@Chazy12 
Have you tried the latest beta version, yet?
There, this issue should be fixed. Please, let me know if you still
see this behaviour in the latest beta version.

Thanks,
Andreas
