### ISSUE TITLE
Kamera

### ISSUE THREAD

**Issue by Babu1970** [AndreasReitberger/RemoteControlRepetierServerProApp#8]
Moin aus dem Norden,
Ich bekomme meine 3 Kameras nicht editiert. Bei der Eingabe bzw. Änderung der Kameras und anschließenden speichern, erscheint immer die Meldung das die Kamera Einstellung O überschrieben wird. 

Ist das ein bekannt ?

gruss und bleibt gesund 

Torben

**Comment by AndreasReitberger** [comment]
Hallo Torben,
vielen Dank für dein Feedback. Du musst für die WebCam-Einstellungen eine einzigartige Kombination aus Printer-Slug und WebCam-Index angeben.

Wenn du zwei Kameras installiert hast, dann kannst du folgende Kombinationen anlegen:
 - Drucker1, CamIndex 0
 - Drucker1, CamIndex 1
 
![image](https://user-images.githubusercontent.com/2952443/111499840-a5d9b900-8743-11eb-9893-d3332bd2ebe8.png)

ist eine Kombination aus Drucker-Slug und WebCam-Index schon vorhanden, dann bekommst du die Meldung.

```
// Check if there are already settings for this printer & cam index
                    var temp = WebCamSettings.FirstOrDefault(settings => settings.Slug == Instance.Slug && settings.CamIndex == Instance.CamIndex);
                    if(temp == null)
                        WebCamSettings.Add(Instance);
                    else
                    {
                        var prompt = await Application.Current.MainPage.DisplayAlert(
                            Strings.DialogWebCamSettingsAlreadyExistsForThisCombinationHeadline,
                            string.Format(Strings.DialogWebCamSettingsAlreadyExistsForThisCombinationFormatedContent, Slug, CamIndex),
                            Strings.Overwrite,
                            Strings.Cancel
                            );
                        if (prompt)
                        {
                            WebCamSettings.Remove(temp);
                            WebCamSettings.Add(Instance);
                        }
                        else
                        {
                            IsBusy = false;
                            return; // Back to form
                        }
```

Sollte die Fehlermeldung doch fälschlicherweise kommen, bitte ich dich ggf. ein kurzes Video oder Screenshots zu teilen.

Viele Grüße aus Ostbayern,
Andreas

**Comment by Babu1970** [comment]
Moin Andreas,
Jupp alles soweit versucht nur macht die App bei mir keine weitere CAM Einstellung auf bzw. speichert diese ....
als Anlage ein paar Screenshots.
Egal welche Kamera ich im Pulldown-Menü auswähle und speichere, kommt die Meldung das er die Kamera 0 überschreiben möchte.

App schon 2x deaktiviert und verschiedene Drucker / Server getestet .

Gruß aus HH

[cid:3A1BC09A-BF85-4858-B77F-869E70FA4C97-L0-001][cid:6824757D-A3E7-4476-B901-C6EB149583B1-L0-001][cid:9CBAB5B6-8004-4944-B45B-80ED233EA53D-L0-001][cid:6A6BAB51-4E4C-4315-A4BB-51BF59BEC16C-L0-001]

Best regards / Mit sportlichen Grüßen

Torben Bröer

Hans-Stockmar-Str 26, 24568 Kaltenkirchen<x-apple-data-detectors://0> / Germany

***@***.***

Tel.: ‭+49 4191 9568744‬
Mob.: +49 170 444 000 8<tel:+49%20170%20444%20000%208>





This message and any files transmitted with it may be confidential and are only intended for the individual named. If you are not the named adressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have recieved this e-mail by mistake and delete this e-mail from your system.


Am 17.03.2021 um 17:12 schrieb Andreas ***@***.***>:

﻿

Hallo Torben,
vielen Dank für dein Feedback. Du musst für die WebCam-Einstellungen eine einzigartige Kombination aus Printer-Slug und WebCam-Index angeben.

Wenn du zwei Kameras installiert hast, dann kannst du folgende Kombinationen anlegen:

  *   Drucker1, CamIndex 0
  *   Drucker1, CamIndex 1

[image]<https://user-images.githubusercontent.com/2952443/111499840-a5d9b900-8743-11eb-9893-d3332bd2ebe8.png>

ist eine Kombination aus Drucker-Slug und WebCam-Index schon vorhanden, dann bekommst du die Meldung.

// Check if there are already settings for this printer & cam index
                    var temp = WebCamSettings.FirstOrDefault(settings => settings.Slug == Instance.Slug && settings.CamIndex == Instance.CamIndex);
                    if(temp == null)
                        WebCamSettings.Add(Instance);
                    else
                    {
                        var prompt = await Application.Current.MainPage.DisplayAlert(
                            Strings.DialogWebCamSettingsAlreadyExistsForThisCombinationHeadline,
                            string.Format(Strings.DialogWebCamSettingsAlreadyExistsForThisCombinationFormatedContent, Slug, CamIndex),
                            Strings.Overwrite,
                            Strings.Cancel
                            );
                        if (prompt)
                        {
                            WebCamSettings.Remove(temp);
                            WebCamSettings.Add(Instance);
                        }
                        else
                        {
                            IsBusy = false;
                            return; // Back to form
                        }


Sollte die Fehlermeldung doch fälschlicherweise kommen, bitte ich dich ggf. ein kurzes Video oder Screenshots zu teilen.

Viele Grüße aus Ostbayern,
Andreas

**Comment by AndreasReitberger** [comment]
@Babu1970 
Hallo Torben,

vielen Dank für deine Rückmeldung. Dann schau ich mir das gleich nochmal an und werde es mit dem nächsten Update beheben.

Viele Grüße,
Andreas

**Comment by AndreasReitberger** [comment]
Hallo Torben,
ich konnte den Fehler identifizieren. Die App hat den Index nicht übernommen, wenn du eine andere Kamera als die erste ausgewählt hast.
Fix kommt mit dem nächsten Update. Sollte das Problem weiter bestehen, öffne bitte einfach dieses oder einen neuen Fehler hier. 
Danke fürs Melden!

Schöne Grüße & alles Gute,
Andreas

**Comment by Babu1970** [comment]
Moin Andreas,
Kamera Setup läuft nach dem Update !

Es grüßt der Norden


Best regards / Mit sportlichen Grüßen

Torben Bröer

Hans-Stockmar-Str 26, 24568 Kaltenkirchen<x-apple-data-detectors://0> / Germany

***@***.***

Tel.: ‭+49 4191 9568744‬
Mob.: +49 170 444 000 8<tel:+49%20170%20444%20000%208>





This message and any files transmitted with it may be confidential and are only intended for the individual named. If you are not the named adressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have recieved this e-mail by mistake and delete this e-mail from your system.


Am 18.03.2021 um 16:20 schrieb Andreas ***@***.***>:

﻿

Closed #8<https://github.com/AndreasReitberger/RemoteControlRepetierServerProApp/issues/8>.

**Comment by AndreasReitberger** [comment]
@Babu1970 
Super, danke für die Rückmeldung :)

Viele Grüße,
Andreas
