### ISSUE TITLE
Temperatures not visible and all settings set as described 

### ISSUE THREAD

**Issue by Weijenberg** [AndreasReitberger/RemoteControlRepetierServerProApp#9]
I have added the printer a prusa mk3s+ as in the documentation is mentioned. But I have two errors.
1. In some cases the drawing is not correct didplayed 70% of the cases( minor issue)
2. The temperature of the extrudes and the bed is not visible. This is possible  also the reason when we remote stop the temperature stays on and can result in a fire as we have explored so be carefully.

please I need some help to use the software as expected and with a failure save shutdown?
Best regards,
Björn

**Comment by AndreasReitberger** [comment]
Hi @Weijenberg 

can you provide some screenshots or a small screen video showing the issues you mentioned?

Not showing extruder and bed temp:
This mostly is the case if the printer is not connected to the server. However if it‘s only sometimes, it could be a bug in the app.

When does this happen? Can you tell me the steps you did to reproduce the issue on my end?

I‘ll check it on my end then.

Best,
Andreas

**Comment by Weijenberg** [comment]
Dear Andreas,
See our answers behind your questions.


Verstuurd vanaf mijn iPhone

**Comment by AndreasReitberger** [comment]
> Dear Andreas, See our answers behind your questions. Verstuurd vanaf mijn iPhone
> […](#)
> Op 3 apr. 2021 om 06:26 heeft Andreas ***@***.***> het volgende geschreven: ﻿ Hi @Weijenberg can you provide some screenshots or a small screen video showing the issues you mentioned? Not showing extruder and bed temp:this is always the case we didn’t see the tempertures This mostly is the case if the printer is not connected to the server. However if it‘s only sometimes, it could be a bug in the app. When does this happen? Can you tell me the steps you did to reproduce the issue on my end? The issue that the bed and extruded are headed after the stop is when we during the print press on the stop button from the display our from the app. I‘ll check it on my end then. Best, Andreas — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi @Weijenberg 
Thank you for you feedback. Do you mean the "Emergency Stop" button?
![image](https://user-images.githubusercontent.com/2952443/113476309-0888bf80-947b-11eb-9555-c5df67b2c299.png)

In this case, the printer will be ejected from the Repetier Server and the printer performs a reboot.
During this, the printer is not reachable and therefore shown as offline. You can go to the printer overview and refresh the page till the printer is back online.

Please see the attached video as demonstration.
https://user-images.githubusercontent.com/2952443/113476537-5b16ab80-947c-11eb-8388-185a953c7810.MP4

Is this the issue you are facing? 
If so, please note that the "Emergency Button" is only there to stop the printer in an emergency case.
If you still think there is a issue with the app, please provide a video or some screenshots showing the faulty behaviour.

Thank you, 
Andreas

**Comment by Weijenberg** [comment]
Thanks Andreas,

Indeed the emergency stop button.
The printer stops but there is no reboot and the temperature are still on.
If there was a reboot the temperature is set back to zero.
But this is not happening.
Is this because we also don’t see any temperature?
When we print?
If you like I can make a video when I do a small print. And do a emergency stop within the first layer.

Best regards,
Björn Weijenberg 


Verstuurd vanaf mijn iPhone

**Comment by AndreasReitberger** [comment]
> Thanks Andreas, Indeed the emergency stop button. The printer stops but there is no reboot and the temperature are still on. If there was a reboot the temperature is set back to zero. But this is not happening. Is this because we also don’t see any temperature? When we print? If you like I can make a video when I do a small print. And do a emergency stop within the first layer. Best regards, Björn Weijenberg Verstuurd vanaf mijn iPhone


Hi @Weijenberg 
a small video would be great. So that I can reproduce the issue on my side.
However, it's strange that your printer doesn't reboot after the emergency button was pressed at all.
I also have a Prusa i3 MK3S connected to my server.
What Repetier Server version do you have running?
I'm currently on 1.0.3

Looking forward to your video. I'll check it on my end then.

Thank you,
Andreas

**Comment by Weijenberg** [comment]
Dear Andreas I have the latest version 1.0.4
What settings do you have and do you seen the nozzle and bed temperature?
I have set the settings as mentioned on the prusa site.
I will make a video after this print.

Best regards,
Björn 

Verstuurd vanaf mijn iPhone

**Comment by Weijenberg** [comment]
Dear Andreas,
Today we have got a crash but we didn’t receive a massage  from the app.
Repetier informer is this also normal?
I expected that we got a message from the app.
I tried to send a smal video as promised but your mail sever from GitHub doesn’t support a bigger file?
Do you got a other mail server we can use?
Best regards,
Björn weijenberg 

Verstuurd vanaf mijn iPhone

**Comment by Weijenberg** [comment]
Dear Andreas we reinstalled the server and the reboot is now working as designed.
The only thing that still not works it the temperature readings from the extruded and the headed bed.
I thing I forgot some thing do you have any suggestion?
How I can solve  this?

Best regards,
Björn 

Verstuurd vanaf mijn iPhone

**Comment by AndreasReitberger** [comment]
Hi @Weijenberg 
Sorry for the long wait, I was working on another project. Please see my replies to your questions below.

**Today we have got a crash but we didn’t receive a massage  from the app.**
Do you mean that your printer got a crash? Or the app stopped working? Also, do you mean the "RC for Repetier Server" app or the "Repetier Informer" app? Latter is not from me, it's an official app by the makers of Repetier Server.

**I tried to send a smal video as promised but your mail sever from GitHub doesn’t support a bigger file?**
Sure, you either can join our new community below
https://andreas-reitberger.de/forum/index.php?/forum/32-english/

or send the video via Google Drive / Dropbox link to my email: kontakt@andreas-reitberger.de
I'll check and fix it with the upcoming release.

The only thing that still not works it the temperature readings from the extruded and the headed bed.
This comes up if you have an invalid API key.
Maybe this video can help:
https://www.youtube.com/watch?v=YSMICzfsVTQ

Please, always share some screenshots at least. This helps a lot to me understanding the issue and make it faster for me to fix it :) 

Thank you,
Andreas

**Comment by Weijenberg** [comment]
Dear Andreas,
We have found the error it was on the server end if the temp devination is set as null in the code instead of 0.
Currently this solves all the errors we have no error anymore.

Thanks for your help and getting us to the right direction what lead to the solution!

Best regards,
Björn 

Verstuurd vanaf mijn iPhone

**Comment by AndreasReitberger** [comment]
Hi @Weijenberg 
I'm glad to hear that!
I'll close this issue then.
Please feel free to open a new issue if you found any problems within the app.

Thank you,
Andreas
